version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nest_app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
  db:
    image: postgres:16
    container_name: nest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_app
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  node_modules: