name: Build and Push Docker

description: Build NestJS app and push Docker image to GHCR
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Lowercase repository owner
      id: repo
      shell: bash
      run: echo "repo_owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build project
      run: npm run build
      shell: bash

    - name: Build Docker image
      shell: bash
      run: docker build -t "$IMAGE" .

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push Docker image
      shell: bash
      run: docker push "$IMAGE"
