name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker build and push action
        uses: ./.github/actions/build-push