name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development
env:
  IMAGE: ghcr.io/${{ steps.repo.outputs.repo_owner_lc }}/ci-cd-app:${{ github.sha }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker build and push action
        uses: ./.github/actions/build-push
        with:
          image_name: ${{ github.repository }}
          token: ${{ github.token }}